package com.example.shopping.config;

import com.example.shopping.dao.ProductCategoryRepository;
import com.example.shopping.dao.ProductRepository;
import com.example.shopping.entity.Product;
import com.example.shopping.entity.ProductCategory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component
public class DatabaseLoader implements CommandLineRunner {

    private ProductRepository productRepository;
    private ProductCategoryRepository productCategoryRepository;

    @Autowired
    public DatabaseLoader(ProductRepository productRepository, ProductCategoryRepository productCategoryRepository) {
        this.productRepository = productRepository;
        this.productCategoryRepository = productCategoryRepository;
    }

    @Override
    public void run(String... args) throws Exception {
        loadBooks();
        loadMugs();
        loadPads();
        loadTags();
    }

    private void loadBooks() {
        ProductCategory book = new ProductCategory("Book");
        book.addProduct(new Product("BOOK-TECH-1000", "Crash Course in Python", "Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1000.png", true, 100, 14.99));
        book.addProduct(new Product("BOOK-TECH-1001", "Become a Guru in JavaScript", "Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1001.png", true, 100, 20.99));
        book.addProduct(new Product("BOOK-TECH-1002", "Exploring Vue.js", "Learn Vue.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1002.png", true, 100, 14.99));
        book.addProduct(new Product("BOOK-TECH-1003", "Advanced Techniques in Big Data", "Learn Big Data at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1003.png", true, 100, 13.99));
        book.addProduct(new Product("BOOK-TECH-1004", "Crash Course in Big Data", "Learn Big Data at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1004.png", true, 100, 18.99));
        book.addProduct(new Product("BOOK-TECH-1005", "JavaScript Cookbook", "Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1005.png", true, 100, 23.99));
        book.addProduct(new Product("BOOK-TECH-1006", "Beginners Guide to SQL", "Learn SQL at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1006.png", true, 100, 14.99));
        book.addProduct(new Product("BOOK-TECH-1007", "Advanced Techniques in JavaScript", "Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1007.png", true, 100, 16.99));
        book.addProduct(new Product("BOOK-TECH-1008", "Introduction to Spring Boot", "Learn Spring Boot at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1008.png", true, 100, 25.99));
        book.addProduct(new Product("BOOK-TECH-1009", "Become a Guru in React.js", "Learn React.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1009.png", true, 100, 23.99));
        book.addProduct(new Product("BOOK-TECH-1010", "Beginners Guide to Data Science", "Learn Data Science at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1010.png", true, 100, 24.99));
        book.addProduct(new Product("BOOK-TECH-1011", "Advanced Techniques in Java", "Learn Java at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1011.png", true, 100, 19.99));
        book.addProduct(new Product("BOOK-TECH-1012", "Exploring DevOps", "Learn DevOps at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1012.png", true, 100, 24.99));
        book.addProduct(new Product("BOOK-TECH-1013", "The Expert Guide to SQL", "Learn SQL at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1013.png", true, 100, 19.99));
        book.addProduct(new Product("BOOK-TECH-1014", "Introduction to SQL", "Learn SQL at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1014.png", true, 100, 22.99));
        book.addProduct(new Product("BOOK-TECH-1015", "The Expert Guide to JavaScript", "Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1015.png", true, 100, 22.99));
        book.addProduct(new Product("BOOK-TECH-1016", "Exploring React.js", "Learn React.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1016.png", true, 100, 27.99));
        book.addProduct(new Product("BOOK-TECH-1017", "Advanced Techniques in React.js", "Learn React.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1017.png", true, 100, 13.99));
        book.addProduct(new Product("BOOK-TECH-1018", "Introduction to C#", "Learn C# at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1018.png", true, 100, 26.99));
        book.addProduct(new Product("BOOK-TECH-1019", "Crash Course in JavaScript", "Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1019.png", true, 100, 13.99));
        book.addProduct(new Product("BOOK-TECH-1020", "Introduction to Machine Learning", "Learn Machine Learning at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1020.png", true, 100, 19.99));
        book.addProduct(new Product("BOOK-TECH-1021", "Become a Guru in Java", "Learn Java at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1021.png", true, 100, 18.99));
        book.addProduct(new Product("BOOK-TECH-1022", "Introduction to Python", "Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1022.png", true, 100, 26.99));
        book.addProduct(new Product("BOOK-TECH-1023", "Advanced Techniques in C#", "Learn C# at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1023.png", true, 100, 22.99));
        book.addProduct(new Product("BOOK-TECH-1024", "The Expert Guide to Machine Learning", "Learn Machine Learning at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!", "assets/images/products/books/book-luv2code-1024.png", true, 100, 16.99));
        productCategoryRepository.save(book);
    }

    private void loadMugs() {
        ProductCategory mug = new ProductCategory("Coffee Mugs");
        mug.addProduct(new Product("COFFEEMUG-1000", "Coffee Mug - Express", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1000.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1001", "Coffee Mug - Cherokee", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1001.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1002", "Coffee Mug - Sweeper", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1002.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1003", "Coffee Mug - Aspire", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1003.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1004", "Coffee Mug - Dorian", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1004.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1005", "Coffee Mug - Columbia", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1005.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1006", "Coffee Mug - Worthing", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1006.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1007", "Coffee Mug - Oak Cliff", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1007.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1008", "Coffee Mug - Tachyon", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1008.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1009", "Coffee Mug - Pan", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1009.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1010", "Coffee Mug - Phase", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1010.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1011", "Coffee Mug - Falling", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1011.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1012", "Coffee Mug - Wispy", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1012.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1013", "Coffee Mug - Arlington", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1013.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1014", "Coffee Mug - Gazing", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1014.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1015", "Coffee Mug - Azura", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1015.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1016", "Coffee Mug - Quantum Leap", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1016.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1017", "Coffee Mug - Light Years", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1017.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1018", "Coffee Mug - Taylor", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1018.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1019", "Coffee Mug - Gracia", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1019.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1020", "Coffee Mug - Relax", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1020.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1021", "Coffee Mug - Windermere", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1021.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1022", "Coffee Mug - Prancer", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1022.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1023", "Coffee Mug - Recursion", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1023.png", true, 100, 18.99));
        mug.addProduct(new Product("COFFEEMUG-1024", "Coffee Mug - Treasure", "Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You dont have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!", "assets/images/products/coffeemugs/coffeemug-luv2code-1024.png", true, 100, 18.99));
        productCategoryRepository.save(mug);
    }

    private void loadPads() {
        ProductCategory pad = new ProductCategory("Mouse Pads");
        pad.addProduct(new Product("MOUSEPAD-1000", "Mouse Pad - Express", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1000.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1001", "Mouse Pad - Cherokee", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1001.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1002", "Mouse Pad - Sweeper", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1002.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1003", "Mouse Pad - Aspire", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1003.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1004", "Mouse Pad - Dorian", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1004.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1005", "Mouse Pad - Columbia", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1005.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1006", "Mouse Pad - Worthing", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1006.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1007", "Mouse Pad - Oak Cliff", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1007.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1008", "Mouse Pad - Tachyon", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1008.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1009", "Mouse Pad - Pan", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1009.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1010", "Mouse Pad - Phase", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1010.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1011", "Mouse Pad - Falling", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1011.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1012", "Mouse Pad - Wispy", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1012.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1013", "Mouse Pad - Arlington", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1013.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1014", "Mouse Pad - Gazing", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1014.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1015", "Mouse Pad - Azura", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1015.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1016", "Mouse Pad - Quantum Leap", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1016.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1017", "Mouse Pad - Light Years", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1017.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1018", "Mouse Pad - Taylor", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1018.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1019", "Mouse Pad - Gracia", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1019.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1020", "Mouse Pad - Relax", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1020.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1021", "Mouse Pad - Windermere", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1021.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1022", "Mouse Pad - Prancer", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1022.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1023", "Mouse Pad - Recursion", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1023.png", true, 100, 17.99));
        pad.addProduct(new Product("MOUSEPAD-1024", "Mouse Pad - Treasure", "Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!", "assets/images/products/mousepads/mousepad-luv2code-1024.png", true, 100, 17.99));
        productCategoryRepository.save(pad);
    }
    private void loadTags() {
        ProductCategory tag = new ProductCategory("Luggage Tags");
        tag.addProduct(new Product("LUGGAGETAG-1000", "Luggage Tag - Cherish", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1000.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1001", "Luggage Tag - Adventure", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1001.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1002", "Luggage Tag - Skyline", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1002.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1003", "Luggage Tag - River", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1003.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1004", "Luggage Tag - Trail Steps", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1004.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1005", "Luggage Tag - Blooming", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1005.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1006", "Luggage Tag - Park", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1006.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1007", "Luggage Tag - Beauty", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1007.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1008", "Luggage Tag - Water Fall", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1008.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1009", "Luggage Tag - Trail", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1009.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1010", "Luggage Tag - Skyscraper", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1010.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1011", "Luggage Tag - Leaf", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1011.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1012", "Luggage Tag - Jungle", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1012.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1013", "Luggage Tag - Shoreline", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1013.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1014", "Luggage Tag - Blossom", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1014.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1015", "Luggage Tag - Lock", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1015.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1016", "Luggage Tag - Cafe", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1016.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1017", "Luggage Tag - Darling", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1017.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1018", "Luggage Tag - Full Stack", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1018.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1019", "Luggage Tag - Courtyard", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1019.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1020", "Luggage Tag - Coaster", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1020.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1021", "Luggage Tag - Bridge", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1021.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1022", "Luggage Tag - Sunset", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1022.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1023", "Luggage Tag - Flames", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1023.png", true, 100, 16.99));
        tag.addProduct(new Product("LUGGAGETAG-1024", "Luggage Tag - Countryside", "This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!", "assets/images/products/luggagetags/luggagetag-luv2code-1024.png", true, 100, 16.99));
        productCategoryRepository.save(tag);
    }
}
